# Generated by Django 5.2 on 2025-04-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Невідомий жанр', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='preview_link',
            field=models.URLField(default='#'),
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(default='https://via.placeholder.com/200x300?text=No+Image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
