# Generated by Django 5.2 on 2025-04-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_book_published_year_book_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
